platform :ios, ‘8.0’ 
target ‘SCGD’ do
pod 'MBProgressHUD', '~> 0.8'
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'Reachability', '~> 3.2'
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.8.1'
pod 'AsyncDisplayKit', '~> 1.9.90'
pod 'UMengAnalytics'
pod ‘Fabric’
pod ‘Crashlytics’
end
